FROM oven/bun:latest
RUN apt-get update
RUN apt-get install -y zsh
RUN apt-get install -y bash
RUN apt-get install -y curl
RUN apt-get install -y git
RUN apt-get install -y openssl
RUN apt-get install -y nodejs
RUN apt-get install -y npm
RUN openssl req -x509 -newkey rsa:2048 -nodes -keyout ssl.key -out ssl.cert -sha256 -days 365 -subj "/C=CH/ST=Vaud/L=Lausanne/O=42/OU=Transcendance/CN=localhost"
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
WORKDIR /app
ENTRYPOINT [ "/bin/zsh" ]
