FROM oven/bun:1.2.22-alpine
RUN apk add --no-cache zsh
RUN apk add --no-cache bash
RUN apk add --no-cache curl
RUN apk add --no-cache git
RUN apk add --no-cache openssl
RUN apk add --no-cache nodejs
RUN apk add --no-cache npm
RUN openssl req -x509 -newkey rsa:2048 -nodes -keyout ssl.key -out ssl.cert -sha256 -days 365 -subj "/C=CH/ST=Vaud/L=Lausanne/O=42/OU=Transcendance/CN=localhost"
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
WORKDIR /app
ENTRYPOINT [ "/bin/zsh" ]
