FROM node:20-alpine as build
WORKDIR /app
COPY . .
RUN corepack enable && corepack install && pnpm install && pnpm run build

FROM nginx:alpine
COPY --from=build /app/build/public /usr/share/nginx/html
EXPOSE 80
