services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./local.db:/app/local.db
    env_file:
      - config/.env

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - .:/app
    ports:
      - "3000:80"
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

