FROM node:24-alpine3.22 AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
RUN apk add --no-cache zsh
RUN apk add --no-cache bash
RUN apk add --no-cache curl
RUN apk add --no-cache git
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
RUN echo 'alias pn="pnpm"' >> ~/.zshrc
RUN echo 'alias px="pnpx"' >> ~/.zshrc
WORKDIR /app
ENTRYPOINT [ "/bin/zsh" ]
